#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If you want to allow non-ascii filenames set this variable to true.
allownonascii="true"

# Cross platform projects tend to avoid non-ascii filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test "$(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0')"
then
	echo "Error: Attempt to add a non-ascii file name."
	echo
	echo "This can cause problems if you want to work"
	echo "with people on other platforms."
	echo
	echo "To be portable it is advisable to rename the file ..."
	echo
	echo "If you know what you are doing you can disable this"
	echo "check using:"
	echo
	echo "  git config hooks.allownonascii true"
	echo
	exit 1
fi

# check php files - only for added, copied, or modified php files
for file in $(git diff --cached --name-only --diff-filter=ACM | grep \.php$ | uniq); do
    if [ -s $file ]; then

      add=""
      # strip tailing whitespace
      space=$(grep -m 1 " $" $file)
      if [ -n "$space" ]; then
          sed -i 's/[[:space:]]*$//' "$file"
          add=1
      fi

      # strip tabs
      tab=$(grep -m 1 -P "\t" $file)
      if [ -n "$tab" ]; then
          sed -i 's/\t/    /g' "$file"
          add=1
      fi

      # " if(" => " if ("
      fix=$(grep -m 1 ' if(' $file)
      if [ -n "$fix" ]; then
          sed -i 's/ if(/ if (/' "$file"
          add=1
      fi
      # " if ( " => " if ("
      fix=$(grep -m 1 ' if ( ' $file)
      if [ -n "$fix" ]; then
          sed -i 's/ if ( / if (/' "$file"
          add=1
      fi

      # " foreach(" => " foreach ("
      fix=$(grep -m 1 ' foreach(' $file)
      if [ -n "$fix" ]; then
          sed -i 's/ foreach(/ foreach (/' "$file"
          add=1
      fi

      # array() => []
      fix=$(grep -P -m 1 '\Warray\(\)' $file)
      if [ -n "$fix" ]; then
          perl -i -pe 's/(\W)array\(\)/$1\[]/' "$file"
          add=1
      fi

      # check php syntax
      result=$(php -l $file)
      if [ $? -ne 0 ]; then
          echo "Invalid PHP file: $file"
          echo $result
          exit 1
      fi

      # if file cleaned, add back to git
      if [ -n "$add" ]; then
          echo "$file cleaned, adding back to git"
          git add $file
      fi
    fi
done

#exec git diff-index --check --cached $against --
